FROM node:alpine
# RUN apk update && apk add git && apk add python make g++
USER root
WORKDIR /app/frontend
COPY package.json /app/frontend

RUN npm install

COPY . /app/frontend

EXPOSE 3000
CMD npm run dev