# Generated by Django 4.0.4 on 2022-05-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
