# Generated by Django 4.0.4 on 2022-05-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dislikesVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='likesVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='lowRateVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
