# Generated by Django 4.0.4 on 2022-05-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('FreelancerPlus', 'FreelancerPlus'), ('Client', 'Client'), ('ClientPlus', 'ClientPlus'), ('Moderator', 'Moderator'), ('Administrator', 'Administrator')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
