# Generated by Django 4.0.4 on 2022-05-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('FreelancerPlus', 'Freelancer Plus'), ('Client', 'Client'), ('ClientPlus', 'Client Plus'), ('Moderator', 'Moderator'), ('Administrator', 'Administrator')], default='Freelancer', max_length=50),
        ),
    ]
